export const GET_PROFILE = "GET_PROFILE";
export const UPLOAD_ID_CARD = "UPLOAD_ID_CARD";
export const OPTIONS_SELECT_HOSTEL = "OPTIONS_SELECT_HOSTEL";
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
